import DarkToggle from '@/component/DarkToggle';
import WeatherUi from '@/component/WeatherUi';
import Head from 'next/head'
import { useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {

  const [loading, setLoading] = useState(false);
  const [weather, setWeather] = useState();
  const [city, setCity] = useState();
  const [enterd, setEnterd] = useState(false)

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=8b743ddae516b7921ca92de27712ba07`;
  const myFunct = async (e) => {
    e.preventDefault();
    setEnterd(true);
    setLoading(true);
    await fetch(url)
      .then(response => response.json())
      .then(response => { setWeather(response) })
      .catch(err => console.error(err));
    setLoading(false);
  }

  const handleChange = (e) => {
    setCity(e.target.value);
    e.preventDefault();
  }

  if (loading) {
    console.log('loading')
  } else if (loading != true) {
    console.log("complete")
  }

  const mounth = ['jan', 'Feb', 'March', 'April', 'May', 'June', 'July', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  const a = new Date();
  const b = a.getDate()
  const c = a.getMonth()
  const d = a.getHours()
  const e = a.getMinutes()

  return (
    <>
      <Head>
        <title>Weather Plus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DarkToggle />
      <div className={styles.main}>
        <div className={styles.section}>
          <div className={styles.nav}>
            <form onSubmit={myFunct} className={styles.form}>
              <div className={styles.inputContainer}>
                <input placeholder="Enter location" onChange={handleChange} className={styles.inputField} type="text" />
                <label htmlFor="input-field" className={styles.inputLabel}>Enter Location</label>
                <span className={styles.inputHighlight}></span>
              </div>

              <div className='mx-3 text-white flex justify-center items-center h-[35px] w-[35px] rounded-full bg-blue-500' onClick={myFunct}>&rarr;</div>
            </form>
            <h3 className='text-white' style={{ fontWeight: "400", fontSize: "1.5rem" }}>{d}:{e} <span style={{ fontSize: "0.8rem" }}>{b} {mounth[c]}</span></h3>
          </div>
          {!enterd &&
            <div className={styles.init}>
              <p>Enter loaction to see Weather</p>
            </div>
          }
          {enterd && <WeatherUi data={weather} loading={loading} />}
        </div>
      </div>
    </>
  )
}
